name: spyfall
description: A fan-made project based off the boardgame Spyfall.

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/text/locations.txt
    - assets/text/test_locations.txt